### ISSUE TITLE
Missing test_models_accuracy.py

### ISSUE THREAD

**Issue by joonro** [QuentinAndre/pyprocessmacro#1]
Hi -

Thank you so much for implementing this. It seems `test_models_accuracy.py` that is mentioned in README is missing - could you please add this so I can run tests when making changes? Thank you so much.

**Comment by QuentinAndre** [comment]
Hi,

Thank you for your kind words! The test_models_accuracy is some unfortunate spaghetti code that I pieced together to make sure that the coefficient estimates match those of the Process macro for SPSS. I added it to the repository.

The codebase would definitely benefit from other tests, that's on my roadmap for the future of the project!
