### ISSUE TITLE
pyprocessmacro crash on newer versions of numpy

### ISSUE THREAD

**Issue by BillmanH** [QuentinAndre/pyprocessmacro#12]
When running the original script I was getting the error: 
`No loop matching the specified signature and casting was found for ufunc inv`
Looking through the stack I found that this error was happening in the `numpy.linalg` function and not in the `pyprocessmacro` module. 

After looking around I found that many of the `numpy` functions expect a dtype _float_ instead of _object_. I was able to fix the issue by going into the `pyprocessmacro.models` and  casting them as float types:

from:
```
y = self._endog
x = self._exog

```
to
```
y = self._endog.astype(float)
x = self._exog.astype(float)
```

I had to do this in a couple of places. Once I did this the module worked perfectly. 

Thanks for this awesome application. If you make me a contributor I'd love to share this modification. I don't think it will work with current versions of numpy.

**Comment by QuentinAndre** [comment]
Thank you for the pull request! I merged it and confirm it works just fine now.
