### ISSUE TITLE
Conda and pyprocessmacro

### ISSUE THREAD

**Issue by christianoruge** [QuentinAndre/pyprocessmacro#14]
Hi.

Is there a way to install pyprocessmacro with Anaconda?

When trying to use conda install pyprocessmacro on my Windows machine I get this output:

--
_**Collecting package metadata (current_repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Collecting package metadata (repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.

PackagesNotFoundError: The following packages are not available from current channels:

  - pyprocessmacro

Current channels:

  - https://repo.anaconda.com/pkgs/main/win-64
  - https://repo.anaconda.com/pkgs/main/noarch
  - https://repo.anaconda.com/pkgs/r/win-64
  - https://repo.anaconda.com/pkgs/r/noarch
  - https://repo.anaconda.com/pkgs/msys2/win-64
  - https://repo.anaconda.com/pkgs/msys2/noarch

To search for alternate channels that may provide the conda package you're
looking for, navigate to

    https://anaconda.org

and use the search bar at the top of the page._
--

PS: I get no results for my search for pyprocessmacro on anaconda.org. 

Kind regards, Christian Ruge

**Comment by QuentinAndre** [comment]
Not right now unfortunately, I am still in the process of adding the package on Conda.

Even if you are using anaconda, you can still do `pip install pyprocessmacro` and use it without any issue. Let me know if you encounter a problem!

**Comment by QuentinAndre** [comment]
I have now uploaded pyprocessmacro to conda. You should now be able to install it using `conda install pyprocessmacro -c conda-forge`.

**Comment by christianoruge** [comment]
Fantastisk!

Tanks😀

Christian

Last ned Outlook for Android<https://aka.ms/ghei36>


________________________________
Fra: Quentin ANDRE <notifications@github.com>
Sendt: onsdag 18. november 2020, 16:32
Til: QuentinAndre/pyprocessmacro
Kopi: christianoruge; Author
Emne: Re: [QuentinAndre/pyprocessmacro] Conda and pyprocessmacro (#14)


Closed #14<https://github.com/QuentinAndre/pyprocessmacro/issues/14>.
