### ISSUE TITLE
Cropped name of first outcome model

### ISSUE THREAD

**Issue by Fran4** [QuentinAndre/pyprocessmacro#15]
Hi Quentin,
first of all thanks for this great library that includes the complete process macro from Hayes!
And found just small bug in one dictionary.
It seems that the first entry in "outcome_models" dictionary is saved only with first character.
Tried it for few models and with different variables. It occured in all tested cases.
Example is attached.
Thank you!

[example.docx](https://github.com/QuentinAndre/pyprocessmacro/files/5392532/example.docx)

**Comment by QuentinAndre** [comment]
Hi, thank you for your kind words and for your interest in the library!

I cannot reproduce the error with my version. Could you please double-check the version number of the library that you are using?

**Comment by Fran4** [comment]
Hi, appologies for late response and after updating to your latest version, this issue disappeared. Thanks
