### ISSUE TITLE
MM_index_summary

### ISSUE THREAD

**Issue by shanaadise** [QuentinAndre/pyprocessmacro#20]
Is there a way to get the moderation mediation index summary into a readable dataframe for model 7?

**Comment by QuentinAndre** [comment]
Hi, 

There was a small bug in the code that prevented you from accessing it. It should now be fixed if you update pyprocessmacro to the latest version (pip install pyprocessmacro==1.0.11).

```python
from pyprocessmacro import Process
import pandas as pd

df = pd.read_csv("MyData.csv")
model_seven = ppm.Process(df, model=7, x="x", m=["m1"], y="y", w="w")
mm_index_summary = model_seven.indirect_model.MM_index_summary()
print(mm_index_summary)
````
