### ISSUE TITLE
p.summary() makes the script crash..

### ISSUE THREAD

**Issue by christianoruge** [QuentinAndre/pyprocessmacro#22]
Hi. I got this problem that my script crashes when running p.summary(). I use model 1 and 4, and the same thing happens in both cases. I've asked a question on StackOverflow, but hasn't got any relevant response yet. Do you have a chance to have look at my question on StackOverflow, or would you rather have me reproduce it her? To see my question on StackOverflow, see link: (https://stackoverflow.com/questions/71250868/why-is-p-summary-causing-my-script-crash-when-running-pyprocessmacro-i-use-mo) 
I really hope you can help me crack this problem!! Kind regards, Christian

**Comment by QuentinAndre** [comment]
Hi Christian,

Thank you for your message. Could you please write down:

* The error message that you see when you call p.summary()?
* Your version of numpy, statsmodels, pandas?

Thank you!

**Comment by christianoruge** [comment]
Hi, @QuentinAndre . 

Thanks for reaching out!
I really appreciate it!

My version of numpy is 1.22.2, statsmodels is version 0.13.2 and pandas is version 1.4.1.
My version of PyProcessMacro is 1.0.11.

I use Python 3.9.9. 

My output is like this:

> > C:\Users\ChristianOttoRuge\AppData\Local\Programs\Python\Python39\lib\site-packages\pyprocessmacro\utils.py:33: DeprecationWarning: the `interpolation=` argument to percentile was renamed to `method=`, which has additional options.
> Users of the modes 'nearest', 'lower', 'higher', or 'midpoint' are encouraged to review the method they. (Deprecated NumPy 1.22)
>   llci = np.percentile(samples, plow * 100, interpolation="lower")
> C:\Users\ChristianOttoRuge\AppData\Local\Programs\Python\Python39\lib\site-packages\pyprocessmacro\utils.py:34: DeprecationWarning: the `interpolation=` argument to percentile was renamed to `method=`, which has additional options.
> Users of the modes 'nearest', 'lower', 'higher', or 'midpoint' are encouraged to review the method they. (Deprecated NumPy 1.22)
>   ulci = np.percentile(samples, phigh * 100, interpolation="higher")
> Process successfully initialized.
> Based on the Process Macro by Andrew F. Hayes, Ph.D. (www.afhayes.com)
> 
> 
> ****************************** SPECIFICATION ****************************
> 
> Model = 4
> 
> Variables:
>     Cons = Cons
>     x = q0044
>     y = q0068
>     m1 = IMabovM
> 
> Sample size:
> 206
> 
> Bootstrapping information for indirect effects:
> Final number of bootstrap samples: 5000
> Number of samples discarded due to convergence issues: 0
> 

Then it crashes...

I'm looking forward to hearing from you!!

**Comment by QuentinAndre** [comment]
Hi Christian,

Thank you for these details. Unfortunately, I was interested in the error message that is displayed after it crashes. I assumed it returned something like this: 

```
  File "<stdin>", line 1, in <module>
  File "/home/andreq/anaconda3/envs/testppm/lib/python3.9/site-packages/pyprocessmacro/process.py", line 1353, in summary
    with pd.option_context("precision", self.options["precision"]):
  File "/home/andreq/anaconda3/envs/testppm/lib/python3.9/site-packages/pandas/_config/config.py", line 426, in __enter__
    self.undo = [(pat, _get_option(pat, silent=True)) for pat, val in self.ops]
  File "/home/andreq/anaconda3/envs/testppm/lib/python3.9/site-packages/pandas/_config/config.py", line 426, in <listcomp>
    self.undo = [(pat, _get_option(pat, silent=True)) for pat, val in self.ops]
  File "/home/andreq/anaconda3/envs/testppm/lib/python3.9/site-packages/pandas/_config/config.py", line 128, in _get_option
    key = _get_single_key(pat, silent)
  File "/home/andreq/anaconda3/envs/testppm/lib/python3.9/site-packages/pandas/_config/config.py", line 116, in _get_single_key
    raise OptionError("Pattern matched multiple keys")
pandas._config.config.OptionError: 'Pattern matched multiple keys'
```
? If so, I believe I have found a fix to the problem, linked to a recent pandas update.

Try `pip install pyprocessmacro==1.0.12`, and tell me if the fix is working.

Best,

Quentin.

**Comment by christianoruge** [comment]
Hi, @QuentinAndre . This is fantastic! It works!!
I installed pyprocessmacro 1.0.12 and everything is fine.
Thanks a lot for great help!
