### ISSUE TITLE
seaborn should be specified as a dependency?

### ISSUE THREAD

**Issue by joonro** [QuentinAndre/pyprocessmacro#3]
Hi,

When I did `pip install pyprocessmacro`, I had it complained about `seaborn`. When I install seaborn with `pip install seaborn` I could install the module successfully - I wonder if `seaborn` should be specified as a dependency?

**Comment by QuentinAndre** [comment]
Yes ! Not sure why the most recent setup file did not include seaborn as a dependency. Should be fixed now.
