### ISSUE TITLE
controls_in="both" does not seem to work

### ISSUE THREAD

**Issue by joonro** [QuentinAndre/pyprocessmacro#6]
Hi - 

Both `controls_in="x_to_m"` and `controls_in="all_to_y"` seem to work, but when I use `controls_in="both"` option, it seems controls are not being added at all. It does say variable names in `Statistical Controls:`, but the outputs do not list any of these variables in both `x_to_m` or `all_to_y` cases. (I tested with model 4 and 7). 

Also I verified that it shows the same results when I don't use any control, so it seems like the control variables are ignored when `controls_in="both"` is used.

**Comment by QuentinAndre** [comment]
Hi, there was a discrepancy between the documentation and the code: the argument to include the controls in all equations should be "all", not "both".

I have fixed the documentation and included an error check in the code. If `controls_in` is not in `['all', 'x_to_m', 'all_to_y']`, it will now raise an error. 

Thanks for the issue!

**Comment by joonro** [comment]
Got it. Thanks for the quick reply!
