### ISSUE TITLE
Install fails with syntax error

### ISSUE THREAD

**Issue by wrobinson-gsu** [QuentinAndre/pyprocessmacro#7]
pip install pyprocessmacro
DEPRECATION: Python 2.7 will reach the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 won't be maintained after that date. A future version of pip will drop support for Python 2.7.
Collecting pyprocessmacro
  Using cached https://files.pythonhosted.org/packages/65/20/f34a67260cc0aaff0de675871089fd3eeccf995c1d738a6444e6b926dffc/PyProcessMacro-0.9.7.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-8NXIVg/pyprocessmacro/setup.py", line 3, in <module>
        import pyprocessmacro
      File "pyprocessmacro/__init__.py", line 6, in <module>
        from .process import Process
      File "pyprocessmacro/process.py", line 4, in <module>
        from .models import OLSOutcomeModel, DirectEffectModel, ParallelMediationModel, LogitOutcomeModel
      File "pyprocessmacro/models.py", line 365
        e[i], be[i], *_ = self._indirect_effect_at(i, {})
                     ^
    SyntaxError: invalid syntax

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-install-8NXIVg/pyprocessmacro/

**Comment by QuentinAndre** [comment]
Hi,

pyprocessmacro is only compatible with Python 3.6+. To use this library, I recommend that you update to the latest version of Python.

**Comment by wrobinson-gsu** [comment]
Yes, sorry. I just saw the prior issue with the same error.
